### ISSUE TITLE
README.MD DISCORD

### ISSUE THREAD

**Issue by harvey0100** [wneessen/arrgo#81]
The Discord Invite link is invalid / expired for support of the bot.
Would appreciate if you updated this :)

**Comment by wneessen** [comment]
The bot is not maintained anymore. Rare has disabled most of the data the bot uses from their public web endpoints, so most of the functionality is not working anymore. Hence I shut down the discord. Anything I can help with, though?

**Comment by harvey0100** [comment]
That's understandable then, no worries I was looking into building something myself.
Then came across your repo which looks perfect Hopefully there is some way round this and still pull data from Rare.

Thanks for your quick response though!

**Comment by wneessen** [comment]
I should archive this repo, to make it more obvious.
Anyways, maybe have a look at this: https://geekya.com/games/sot/profile-viewer - That's what I use nowadays.

**Comment by 2called-chaos** [comment]
> Anyways, maybe have a look at this: https://geekya.com/games/sot/profile-viewer - That's what I use nowadays.

I may have created that thing. If you are missing anything let me know =) I also might have a few other treasures in the hold that aren’t charted on the public map just yet.

**Comment by wneessen** [comment]
> > Anyways, maybe have a look at this: https://geekya.com/games/sot/profile-viewer - That's what I use nowadays.
> 
> I may have created that thing. If you are missing anything let me know =) I also might have a few other treasures in the hold that aren’t charted on the public map just yet.

Ha, nice! Appreciate the work you put into it.
